version: '3.7'
services:
  mysql:
    image: postgres:latest
    ports:
      - '9999:9999'
	volumes:
	  - ./data:/var/lib/postgres
	environment:
	  - MYSQL_RANDOM_ROOT_PASSWORD=yes
	  - MYSQL_DATABASE=app
	  - MYSQL_USER=app
	  - MYSQL_PASSWORD=9mREsvXDs9Gk89Ef